server:
  port: 9001
  servlet:
    session:
      timeout: 2m
  error:
    include-stacktrace: always
    include-exception: true
    include-message: always
  
  
logging:
 level:
   root: info
   '[org.springframework]': error
   '[com.danubehome]': info

spring:
  profiles:
    active:
    - "prod"
  main:
    jvmArgs: -Xmx512m
    banner-mode: off
  thymeleaf:
    suffix: .html
    cache: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.SQLServer2016Dialect
  cache:
    type: none
  messages:
    basename: validation
  session:
    store-type: none    
---
###### local server details
spring:
  config:
    activate:
      on-profile: "local"
  

    

########DB DETAILS
security:
  datasource:
    username: sa
    password: Tspl@#2022
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=FMLSTAGE;encrypt=true;trustServerCertificate=true;

      
dbo:
  datasource:
    username: sa
    password: Tspl@#2022
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=FMLSTAGE;encrypt=true;trustServerCertificate=true;
      
server:
  address: 127.0.0.1  
---

###### development / uat server details
spring:
  config:
    activate:
      on-profile: "dev"

server:
  address: 10.72.3.2

########## DB DETAILS
########DB DETAILS
security:
  datasource:
    username: fmluser
    password: fml123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://INP106A\\MSSQLSERVER2019:1443;databaseName=FMLSTAGE;encrypt=true;trustServerCertificate=true;

      
dbo:
  datasource:
    username: fmluser
    password: fml123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://INP106A\\MSSQLSERVER2019:1443;databaseName=FMLSTAGE;encrypt=true;trustServerCertificate=true;


---
###### production server details
spring:
  config:
    activate:
      on-profile: "prod"
       
##### hosting server   
server:
  address: 10.72.251.74
########DB DETAILS

security:
  datasource:
    username: fmluser
    password: fml123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://INP106A\\MSSQLSERVER2019:1443;databaseName=FMLPROD;encrypt=true;trustServerCertificate=true;

      
dbo:
  datasource:
    username: fmluser
    password: fml123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://INP106A\\MSSQLSERVER2019:1443;databaseName=FMLPROD;encrypt=true;trustServerCertificate=true;

  
